export const SET_CURRENT_USER ="SET_CURRENT_USER";

export const SIGN_IN_TOGGLER ="SIGN_IN_TOGGLER";

export const SIGN_IN_AS_MANUFACTURE ="SIGN_IN_AS_MANUFACTURE";

export const SIGN_IN_AS_INVESTOR ="SIGN_IN_AS_INVESTOR";

export const CART_TOGGLER = "CART_TOGGLER";

export const ADD_TO_CART ="ADD_TO_CART";

export const CLEAR_ITEM_FROM_CART ="CLEAR_ITEM_FROM_CART";

export const REMOVE_ITEM_FROM_CART ="REMOVE_ITEM_FROM_CART";

// export const GET_DATA_FROM_FIRESTORE ="GET_DATA_FROM_FIRESTORE";

export const FETCHING_COLLECTION_ASYNC = "FETCHING_COLLECTION_ASYNC";

export const ON_FETCH_START ="FETCH_START";

export const ON_FETCH_SUCCESS ="ON_FETCH_SUCCESS";


export const ON_FETCH_FAILURE ="ON_FETCH_FAILURE";
